import sys
import json
from fpdf import FPDF
from fpdf.enums import XPos, YPos
import requests
import io

class ReportPDF(FPDF):
    def __init__(self, meta_data):
        super().__init__()
        self.meta = meta_data

    def header(self):
        # Logo
        logo_url = self.meta.get('school_logo')
        if logo_url:
            try:
                response = requests.get(logo_url, timeout=5)
                if response.status_code == 200:
                    img_data = io.BytesIO(response.content)
                    self.image(img_data, 10, 8, 33)
            except:
                pass 

        # Font
        self.set_font('Helvetica', 'B', 15)
        
        # Title
        title = self.meta.get('school_name', 'Report')
        w = self.get_string_width(title) + 6
        self.set_x((210 - w) / 2)
        self.cell(w, 9, title, border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
        
        # Address
        self.set_font('Helvetica', '', 10)
        self.cell(0, 5, self.meta.get('address', ''), border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
        self.ln(20)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 5, self.meta.get('disclaimer', ''), border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
        self.cell(0, 5, f'Page {self.page_no()}/{{nb}}', border=0, new_x=XPos.RIGHT, new_y=YPos.TOP, align='R')

def main():
    try:
        # Read input from PHP via STDIN
        # Use buffer to read raw bytes, then decode to handle special chars correctly
        input_data = sys.stdin.buffer.read().decode('utf-8')
        if not input_data:
            return
        parsed_data = json.loads(input_data)
    except Exception as e:
        sys.stderr.write(str(e))
        return

    meta = parsed_data.get("print_meta", {})
    students = parsed_data.get("data", [])
    chart_requests = parsed_data.get("charts", {})

    pdf = ReportPDF(meta)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- Info Block ---
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 5, f"Generated By: {meta.get('generated_by', 'N/A')}", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 5, f"Date: {meta.get('generated_at', 'N/A')}", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    # Show active filters in PDF header if provided
    active_filters = meta.get('active_filters', {})
    if active_filters:
        pdf.ln(2)
        # Filter out empty values for display
        filter_str = [f"{k}: {v}" for k,v in active_filters.items() if v]
        if filter_str:
            filter_text = "Filters Applied: " + ", ".join(filter_str)
            pdf.set_font('Helvetica', 'I', 9)
            pdf.multi_cell(0, 5, filter_text, border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(5)

    if not students:
        pdf.cell(0, 10, "No records found matching criteria.", border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align='C')
    else:
        # --- Dynamic Table Generation ---
        # 1. Identify Columns
        keys = list(students[0].keys())
        
        # 2. Calculate Column Widths
        col_widths = {}
        pdf.set_font('Helvetica', 'B', 10) 
        for key in keys:
            header_text = key.replace("_", " ").title()
            col_widths[key] = pdf.get_string_width(header_text) + 6

        pdf.set_font('Helvetica', '', 9)
        for student in students:
            for key in keys:
                val = str(student.get(key, ""))
                w = pdf.get_string_width(val) + 6
                if w > col_widths[key]:
                    col_widths[key] = w

        # 3. Normalize widths to page size (approx 190mm)
        available_page_width = 190
        total_calc_width = sum(col_widths.values())
        final_widths = []
        for key in keys:
            if total_calc_width > 0:
                ratio = col_widths[key] / total_calc_width
                final_widths.append(ratio * available_page_width)
            else:
                final_widths.append(available_page_width / len(keys))

        # 4. Draw Header
        pdf.set_fill_color(230, 230, 230)
        pdf.set_font('Helvetica', 'B', 10)
        for i, key in enumerate(keys):
            header_text = key.replace("_", " ").title()
            pdf.cell(final_widths[i], 8, header_text, border=1, new_x=XPos.RIGHT, new_y=YPos.TOP, align='C', fill=True)
        pdf.ln()

        # 5. Draw Rows
        pdf.set_font('Helvetica', '', 9)
        for student in students:
            for i, key in enumerate(keys):
                val = str(student.get(key, ""))
                pdf.cell(final_widths[i], 8, val, border=1, new_x=XPos.RIGHT, new_y=YPos.TOP, align='C')
            pdf.ln()

    # Output PDF
    pdf_bytes = pdf.output() 
    sys.stdout.buffer.write(pdf_bytes)

if __name__ == "__main__":
    main()