import matplotlib
matplotlib.use('Agg') # Non-interactive backend
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import pandas as pd
import numpy as np
import sys
import json
import os
import math
import textwrap

# Try to apply a style
try:
    plt.style.use('ggplot')
except:
    pass

def process_charts(config):
    requests = config.get('requests', [])
    output_dir = config.get('output_dir', 'storage')
    
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    response = {
        "pdf": None,
        "images": []
    }

    pdf_filename = f"report_{config.get('job_id', 'temp')}.pdf"
    pdf_path = os.path.join(output_dir, pdf_filename)
    
    try:
        with PdfPages(pdf_path) as pdf:
            for req in requests:
                try:
                    # --- 1. Parse & Validate ---
                    data = req.get('data')
                    chart_type = req.get('type', 'bar').lower()
                    key_col = req.get('key_col')
                    title = req.get('title', 'Untitled')
                    fname = req.get('filename', 'chart')
                    
                    # New fields for Footer
                    uid = req.get('uid', 'Unknown')
                    description = req.get('description', '')
                    
                    # Wrap title text
                    display_title = "\n".join(textwrap.wrap(title, width=60))

                    df = pd.DataFrame(data)
                    
                    if df.empty or key_col not in df.columns:
                        sys.stderr.write(f"Skipping {title}: Data empty or key column missing.\n")
                        continue 

                    df.set_index(key_col, inplace=True)
                    df.fillna(0, inplace=True)

                    # Calculate Total for Metadata
                    total_count = 0
                    numeric_cols = df.select_dtypes(include=['number']).columns
                    if len(numeric_cols) > 0:
                        total_count = df[numeric_cols[0]].sum()

                    # --- Helper: Add Footer Metadata ---
                    def add_footer_metadata():
                        # Bottom Right: Total Count
                        plt.figtext(0.99, 0.01, f"Total Count: {int(total_count)}", horizontalalignment='right', fontsize=8, color='gray')
                        
                        # Bottom Left: UID and Description
                        footer_text = f"Generated by: {uid}"
                        if description:
                            footer_text += f"\n{description}"
                        plt.figtext(0.01, 0.01, footer_text, horizontalalignment='left', fontsize=8, color='gray')

                    # --- 2. Handle Chart Types ---

                    # === TYPE: STATISTICAL TABLE ===
                    if chart_type == 'table':
                        if len(numeric_cols) > 0:
                            df = df.sort_values(by=numeric_cols[0], ascending=False)

                        df_reset = df.reset_index().round(2)
                        
                        if len(numeric_cols) > 0:
                            summary_row = {col: '' for col in df_reset.columns}
                            summary_row[df_reset.columns[0]] = "TOTAL"
                            for col in numeric_cols:
                                summary_row[col] = df[col].sum()
                            df_reset.loc[len(df_reset)] = summary_row

                        all_values = [[str(x) for x in row] for row in df_reset.values]
                        col_labels = df_reset.columns.to_list()
                        
                        ROWS_PER_PAGE = 30
                        total_rows = len(all_values)
                        total_pages = math.ceil(total_rows / ROWS_PER_PAGE)

                        for page in range(total_pages):
                            fig, ax = plt.subplots(figsize=(8.27, 11.69))
                            ax.axis('off')

                            start_row = page * ROWS_PER_PAGE
                            end_row = min((page + 1) * ROWS_PER_PAGE, total_rows)
                            page_data = all_values[start_row:end_row]

                            table = ax.table(cellText=page_data, colLabels=col_labels, loc='upper center', cellLoc='center')
                            table.auto_set_font_size(False)
                            table.set_fontsize(10)
                            table.scale(1, 1.4)

                            for (row, col), cell in table.get_celld().items():
                                if row == 0:
                                    cell.set_text_props(weight='bold', color='white')
                                    cell.set_facecolor('#4a4a4a')
                                elif row % 2 == 0:
                                    cell.set_facecolor('#f2f2f2')

                            page_title = display_title
                            if total_pages > 1:
                                page_title += f"\n(Page {page + 1}/{total_pages})"
                            
                            plt.title(page_title, pad=20, fontweight='bold', y=0.95)
                            
                            # Add Footer to Table
                            add_footer_metadata()

                            pdf.savefig(fig, bbox_inches='tight')
                            
                            if page == 0:
                                img_filename = f"{fname}_{config.get('job_id')}.png"
                                img_path = os.path.join(output_dir, img_filename)
                                plt.savefig(img_path, format='png', dpi=100, bbox_inches='tight')
                                response['images'].append({"id": fname, "path": img_filename})

                            plt.close(fig)

                    # === TYPE: VISUAL CHARTS ===
                    else:
                        fig, ax = plt.subplots(figsize=(10, 6))
                        kind = chart_type
                        
                        if chart_type == 'pie':
                            if len(numeric_cols) > 0 and df[numeric_cols[0]].sum() > 0:
                                df.plot.pie(y=numeric_cols[0], ax=ax, autopct='%1.1f%%', legend=False)
                                ax.set_ylabel('')
                            else:
                                ax.text(0.5, 0.5, "No Data (Sum is 0)", ha='center')

                        elif chart_type == 'scatter':
                            df_scat = df.reset_index()
                            num_cols = df_scat.select_dtypes(include=['number']).columns
                            if len(num_cols) >= 2:
                                df_scat.plot.scatter(x=num_cols[0], y=num_cols[1], ax=ax, s=50)
                            else:
                                ax.text(0.5, 0.5, "Scatter requires 2+ numeric cols", ha='center')
                        
                        else:
                            if chart_type == 'kde':
                                try: import scipy
                                except: kind = 'hist'
                            
                            if not df.empty:
                                chart_plot = df.plot(kind=kind, ax=ax, rot=45 if len(df) > 8 else 0)
                                ax.set_xlabel(key_col)
                                ax.set_ylabel("Values")
                                if len(ax.get_legend_handles_labels()[1]) > 0:
                                    ax.legend(title="Legend")
                                
                                if kind in ['bar', 'barh']:
                                    for p in ax.patches:
                                        if p.get_height() > 0:
                                            ax.annotate(str(int(p.get_height())), 
                                                        (p.get_x() + p.get_width() / 2., p.get_height()), 
                                                        ha='center', va='center', 
                                                        xytext=(0, 5), textcoords='offset points', fontsize=9)
                            else:
                                ax.text(0.5, 0.5, "No Data", ha='center')
                                
                            plt.grid(True, linestyle='--', alpha=0.5)

                        plt.title(display_title)
                        
                        # Add Footer to Chart
                        add_footer_metadata()
                        
                        plt.tight_layout()

                        # Save
                        img_filename = f"{fname}_{config.get('job_id')}.png"
                        img_path = os.path.join(output_dir, img_filename)
                        plt.savefig(img_path, format='png', dpi=100, bbox_inches='tight')
                        response['images'].append({"id": fname, "path": img_filename})

                        pdf.savefig(fig, bbox_inches='tight')
                        plt.close(fig)

                except Exception as e:
                    sys.stderr.write(f"Error processing {title}: {str(e)}\n")
                    continue

    except Exception as e:
        return {"error": str(e)}

    response['pdf'] = pdf_filename
    return response

if __name__ == "__main__":
    try:
        if len(sys.argv) < 2:
            print(json.dumps({"error": "No input file provided"}))
            sys.exit(1)

        input_file = sys.argv[1]
        with open(input_file, 'r') as f:
            config = json.load(f)

        result = process_charts(config)
        print(json.dumps(result))

    except Exception as e:
        print(json.dumps({"error": str(e)}))